// Get references to elements
const airlineForm = document.getElementById("airlineForm");
const airlineNameInput = document.getElementById("airlineName");
const airlineIndexInput = document.getElementById("airlineIndex");
const addBtn = document.getElementById("addBtn");
const updateBtn = document.getElementById("updateBtn");
const airlinesList = document.getElementById("airlinesList");

// Generate a unique ID using Math
function generateUniqueId() {
  return Math.random().toString(36).substring(2, 15);
}

// Load airlines from Local Storage
function loadAirlines() {
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  displayAirlines(airlines);
}

// Display airlines in the table
function displayAirlines(airlines) {
  airlinesList.innerHTML = "";
  airlines.forEach((airline) => {
    const row = document.createElement("tr");

    row.innerHTML = `
      <td>${airline.id}</td>
      <td>${airline.name}</td>
      <td>
        <button class="btn btn-warning btn-sm" onclick="editAirline('${airline.id}')">Edit</button>
        <button class="btn btn-danger btn-sm" onclick="deleteAirline('${airline.id}')">Delete</button>
      </td>
    `;
    airlinesList.appendChild(row);
  });
}

// Save a new or updated airline
function saveAirline(event) {
  event.preventDefault();
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const airlineName = airlineNameInput.value.trim();
  const id = airlineIndexInput.value || generateUniqueId();

  if (airlineIndexInput.value) {
    // Update existing airline by ID
    const airline = airlines.find((airline) => airline.id === id);
    if (airline) {
      airline.name = airlineName;
    }
  } else {
    // Add new airline with a unique ID generated by Math
    airlines.push({ id, name: airlineName });

  }

  localStorage.setItem("airlines", JSON.stringify(airlines));
  loadAirlines();
  console.log(localStorage.getItem("airlines"));

  resetForm();

}

// Edit airline
function editAirline(id) {
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const airline = airlines.find((airline) => airline.id === id);
  if (airline) {
    airlineNameInput.value = airline.name;
    airlineIndexInput.value = id;
    addBtn.classList.add("d-none");
    updateBtn.classList.remove("d-none");
  }
}

// Delete airline
function deleteAirline(id) {
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const updatedAirlines = airlines.filter((airline) => airline.id !== id);
  localStorage.setItem("airlines", JSON.stringify(updatedAirlines));
  loadAirlines();
}

// Reset form after updating
function resetForm() {
  airlineNameInput.value = "";
  airlineIndexInput.value = "";
  addBtn.classList.remove("d-none");
  updateBtn.classList.add("d-none");
}

// Event listeners
airlineForm.addEventListener("submit", saveAirline);
updateBtn.addEventListener("click", saveAirline);

// Load airlines on page load
loadAirlines();